### ISSUE TITLE
Forced declaration of layer order at the beginning of `<head>` causes styles to be overridden by other layers such as the Tailwind base layer

### ISSUE THREAD

**Issue by luangong** [primefaces/primeuix#95]
Our project uses Angular 19, PrimeNG 19.1.3, and Tailwind CSS 4.1.11. If we use the CSS layer feature and declare the following in `app.config.ts`:

```ts
providePrimeNG({
  theme: {
    preset: theme,
    options: {
      cssLayer: {
        name: 'primeng',
      },
    },
  },
}), 
```

then `@primeng/themes@19.1.3` will insert the `@layer primeui` declaration at the beginning of the `<head>` element in `index.html` and wrap PrimeNG component styles with `@layer primeng { ... }` (note that the layer name in the layer order declaration is different from the actual layer name declaration):

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <style type="text/css" data-primeng-style-id="layer-order">@layer primeui</style>

    <!-- other stuff -->

    <link rel="stylesheet" href="styles.css">

    <style type="text/css" data-primeng-style-id="primitive-variables">@layer primeng { ... }</style>
    <style type="text/css" data-primeng-style-id="semantic-variables">@layer primeng { ... }</style>
    <style type="text/css" data-primeng-style-id="global-variables">@layer primeng { ... }</style>
    <style type="text/css" data-primeng-style-id="global-style">@layer primeng { ... }</style>

    <!-- other stuff -->
  </head>

  <body>
    <!-- body content -->
  </body>
</html>
```

This allows us to declare the layer order in `src/styles.css` like this:

```css
@layer theme, base, primeng, primeicons, components, utilities;
```

Previously, when using PrimeNG 19.1.3, component themes came from `@primeng/themes@19.1.3`. However, after upgrading to PrimeNG 20.0.0-rc.1, we switched to using `@primeuix/themes@1.2.0` directly. Now `@primeuix/themes` inserts a layer order declaration matching the value of `cssLayer.name`, causing the layer of PrimeNG styles to be before all other layers. As a result, PrimeNG component styles get overridden by Tailwind CSS’s base layer, making PrimeNG components appear unstyled, like this:

<p align="center">
  <img width="453" alt="Image" src="https://github.com/user-attachments/assets/677a121e-6c38-4e4c-9ae6-dec6290e187c" />
  &nbsp;&nbsp;
  <img width="312" alt="Image" src="https://github.com/user-attachments/assets/4d74ea8b-7494-4083-ba83-7b7cf42127c9" />
</p>

A temporary workaround is to declare both `cssLayer.name` and `cssLayer.order: 'dummy'`, which causes `@primeuix/themes` to insert `@layer dummy` into the `<head>` section of `index.html`, and thus not to interfere with the layer order declaration in `src/styles.css`.

The expected behavior should be: if we don’t declare the `cssLayer.order` property, `@primeuix/themes` shouldn’t insert any layer order declarations in the `<head>` section of `index.html`.

**Comment by mertsincan** [comment]
Fixed for 20.Final. Please try the latest version.

**Comment by luangong** [comment]
The issue persists even with `primeng@20.0.1` and `@primeuix/themes@1.2.3`.
